// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuqigRvbqL4QyQTQwFiB6DsNFFwohcOw',
    appId: '1:645739443904:web:1fd8694692c6f0557f9f25',
    messagingSenderId: '645739443904',
    projectId: 'kelimeoyunu-d3cf9',
    authDomain: 'kelimeoyunu-d3cf9.firebaseapp.com',
    storageBucket: 'kelimeoyunu-d3cf9.appspot.com',
    measurementId: 'G-QSSJ8ESXEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rgP-K9de-iJS31i3Qe-INrxLbZxefWs',
    appId: '1:645739443904:android:814be6cba52e54457f9f25',
    messagingSenderId: '645739443904',
    projectId: 'kelimeoyunu-d3cf9',
    storageBucket: 'kelimeoyunu-d3cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlQZsZPDGBAID_Rk0HbmvX2RchrdXzQA',
    appId: '1:645739443904:ios:d0ef67565d7da45a7f9f25',
    messagingSenderId: '645739443904',
    projectId: 'kelimeoyunu-d3cf9',
    storageBucket: 'kelimeoyunu-d3cf9.appspot.com',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlQZsZPDGBAID_Rk0HbmvX2RchrdXzQA',
    appId: '1:645739443904:ios:d0ef67565d7da45a7f9f25',
    messagingSenderId: '645739443904',
    projectId: 'kelimeoyunu-d3cf9',
    storageBucket: 'kelimeoyunu-d3cf9.appspot.com',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDuqigRvbqL4QyQTQwFiB6DsNFFwohcOw',
    appId: '1:645739443904:web:b8ddb93a0031d0237f9f25',
    messagingSenderId: '645739443904',
    projectId: 'kelimeoyunu-d3cf9',
    authDomain: 'kelimeoyunu-d3cf9.firebaseapp.com',
    storageBucket: 'kelimeoyunu-d3cf9.appspot.com',
    measurementId: 'G-J208W0LGH9',
  );
}
